Force an agent for each parallel stage
To avoid conflict like this

```
---> Running in a1855d049c6f

Removing intermediate container a1855d049c6f

 ---> b134bc6c1cb3

Successfully built b134bc6c1cb3

Successfully tagged jenkinsciinfra/evergreen-backend:latest

Image for service backend was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.

Creating infraevergreenpr95d6lei27mpdy4xpni7yv3lfayry3wnmjzk3mue42dps736bjy5xya_db_1 ...

Creating infraevergreenpr95d6lei27mpdy4xpni7yv3lfayry3wnmjzk3mue42dps736bjy5xya_db_1 ... error

ERROR: for infraevergreenpr95d6lei27mpdy4xpni7yv3lfayry3wnmjzk3mue42dps736bjy5xya_db_1  Cannot create container for service db: Conflict. The container name "/infraevergreenpr95d6lei27mpdy4xpni7yv3lfayry3wnmjzk3mue42dps736bjy5xya_db_1" is already in use by container "984d2c8bc9e0de2b526717963d8808904d1bd58768deb6622b64aead323534df". You have to remove (or rename) that container to be able to reuse that name.



ERROR: for db  Cannot create container for service db: Conflict. The container name "/infraevergreenpr95d6lei27mpdy4xpni7yv3lfayry3wnmjzk3mue42dps736bjy5xya_db_1" is already in use by container "984d2c8bc9e0de2b526717963d8808904d1bd58768deb6622b64aead323534df". You have to remove (or rename) that container to be able to reuse that name.

Encountered errors while bringing up the project.

CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES

6b90a47d7ad9        postgres:alpine     "docker-entrypoint.s…"   5 minutes ago       Up 2 minutes        5432/tcp            services_db_1

Error: No such container:

shunit2:FATAL oneTimeSetUp() returned non-zero return code.

ASSERT:Unknown failure encountered running a test



Ran 0 tests.



FAILED (failures=1)

Makefile:31: recipe for target 'base-container-check' failed

make: *** [base-container-check] Error 2

script returned exit code 2
```