[JENKINS-53318] Force docker-commons:1.9 and token-macro:2.3
Temporary fix to avoid crashing during startup with

```
[SEVERE][2018-08-31 05:54:19] Failed Loading plugin Docker plugin v1.1.5 (docker-plugin) (from jenkins.InitReactorRunner$1 onTaskFailed)
java.io.IOException: Docker plugin v1.1.5 failed to load.
 - Docker Commons Plugin v1.5 is older than required. To fix, install v1.9 or later.
 - Token Macro Plugin v2.0 is older than required. To fix, install v2.3 or later.
        at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:652)
        at hudson.PluginManager$2$1$1.run(PluginManager.java:517)
        at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
        at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
        at jenkins.model.Jenkins$5.runTask(Jenkins.java:1066)
        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```