Fix 'Cannot assign to 'level' because it is a constant or a read-only property.'
```
src/client.ts:186:10 - error TS2540: Cannot assign to 'level' because it is a constant or a read-only property.

186   logger.level = process.env.LOG_LEVEL || 'warn';
             ~~~~~

make: *** [Makefile:14: compile] Error 2
```

See https://github.com/Microsoft/TypeScript/issues/6751#issuecomment-269162714
and https://stackoverflow.com/questions/38818475/left-hand-side-of-assignment-expression-cannot-be-a-constant-or-a-read-only-prop/38833920#38833920